export const SHOW_DETAILS_LOAD_REQUEST = '[SHOW] SHOW_DETAILS_LOAD_REQUEST';
export const SHOW_DETAILS_LOAD_SUCCESS = '[SHOW] SHOW_DETAILS_LOAD_SUCCESS';
export const SHOW_DETAILS_LOAD_FAIL = '[SHOW] SHOW_DETAILS_LOAD_FAIL';

export const SHOW_EPISODE_LIST_LOAD_REQUEST = '[SHOW] SHOW_EPISODE_LIST_LOAD_REQUEST';
export const SHOW_EPISODE_LIST_LOAD_SUCCESS = '[SHOW] SHOW_EPISODE_LIST_LOAD_SUCCESS';
export const SHOW_EPISODE_LIST_LOAD_FAIL = '[SHOW] SHOW_EPISODE_LIST_LOAD_FAIl';