export const EPISODE_DETAILS_LOAD_REQUEST = '[EPISODE] EPISODE_DETAILS_LOAD_REQUEST';
export const EPISODE_DETAILS_LOAD_SUCCESS = '[EPISODE] EPISODE_DETAILS_LOAD_SUCCESS';
export const EPISODE_DETAILS_LOAD_FAIL = '[EPISODE] EPISODE_DETAILS_LOAD_FAIL';
